language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
    include:
        - php: 5.5
        - php: 5.6
        - php: 7.0
        - php: hhvm
        - php: nightly

    allow_failures:
        - php: nightly

    fast_finish: true

before_script:
    - composer self-update
    - composer global require --prefer-source fxp/composer-asset-plugin:@beta
    - composer install --prefer-source
    - composer require --dev --no-update satooshi/php-coveralls:@dev
    - composer update --prefer-source satooshi/php-coveralls
    - mkdir -p ./build/logs

script:
    - ./vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml

after_script:
    - 'echo ''coverage_clover: build/logs/clover.xml'' >> ./.coveralls.yml'
    - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ] && [ "$TRAVIS_PHP_VERSION" != "nightly" ]; then php ./vendor/bin/coveralls -v; fi;'

notifications:
    email: false
